import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#dfe3e7",
        "primary-container": "#d73a02",
        "surface-container-high": "#e4e9ed",
        "surface-container": "#eaeef2",
        "surface-variant": "#dfe3e7",
        "on-primary-container": "#fffbff",
        primary: "#ad2c00",
        "tertiary-fixed-dim": "#bec6e0",
        "on-tertiary-fixed-variant": "#3f465c",
        "tertiary-fixed": "#dae2fd",
        tertiary: "#545c72",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#ffb5a0",
        "primary-fixed-dim": "#ffb5a0",
        error: "#ba1a1a",
        "secondary-fixed": "#ffdbd1",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#3b0900",
        "tertiary-container": "#6c748b",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "surface-dim": "#d6dade",
        secondary: "#aa3612",
        "on-secondary-fixed": "#3b0900",
        "on-error": "#ffffff",
        background: "#f6fafe",
        "on-background": "#171c1f",
        surface: "#f6fafe",
        "outline-variant": "#e4beb4",
        "on-secondary-container": "#681700",
        "on-tertiary-container": "#fefcff",
        outline: "#907067",
        "surface-bright": "#f6fafe",
        "on-surface-variant": "#5b4039",
        "secondary-container": "#ff734b",
        "on-secondary-fixed-variant": "#872100",
        "inverse-surface": "#2c3134",
        "on-surface": "#171c1f",
        "on-primary-fixed-variant": "#872100",
        "inverse-on-surface": "#edf1f5",
        "surface-tint": "#b12e00",
        "primary-fixed": "#ffdbd1",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#131b2e",
        "secondary-fixed-dim": "#ffb5a0",
        "surface-container-low": "#f0f4f8",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-xs": "0.5rem",
        "container-max": "1280px",
        "stack-lg": "2rem",
        gutter: "1.5rem",
        "stack-md": "1rem",
        "margin-mobile": "1rem",
        "margin-desktop": "2.5rem",
      },
      fontFamily: {
        sans: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.03em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.04em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "-0.02em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
export default config;

