services:
  frontend:
    build:
      target: builder
    volumes:
      - ./apps/web:/app/apps/web
      - /app/apps/web/node_modules
      - /app/apps/web/.next
    command: npm run dev --workspace=apps/web
